# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    mkdir mnt 
    ls -R
    cp -R Demo mnt/.
    ls -R
    echo $"license.network.auth.enabled=true
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=admin
    soatest.license.network.edition=automation_edition
    soatest.license.use_network=true
    virtualize.license.network.edition=performance_server_edition
    virtualize.license.use_network=true" >> mnt/localsettings.properties
    ls -R
    cat mnt/localsettings.properties
  displayName: "Set Up the /mnt/localsettings.properties file"

# Mount Settings and Tests and Run
- script: |
    ls -R
    docker --version
    docker run -i \
    -e ACCEPT_EULA=true \
    -v "$(Build.Repository.LocalPath)/mnt:/mnt" \
    parasoft/soavirt /bin/bash -c " \
    ls /mnt; \
    cat /mnt/localsettings.properties; \
    soatestcli \
    -config 'user://Example Configuration' \
    -resource TestAssets \
    -settings /mnt/localsettings.properties \
    "
  workingDirectory: 
  displayName: Mount the Project contents to SOAtest CLI Docker Container adn Run tests 

### Import project into the workspace
# - task: Docker@2
#   displayName: run
#   inputs: 
#     command: run
#     arguments: '-t --network=host -e ACCEPT_EULA=true -v ${pwd}/Demo:/mnt/Demo parasoft/soavirt soatestcli -import /mnt/Demo'

### Run Project
# - task: Docker@2
#   displayName: run
#   inputs: 
#     command: run
#     arguments: '-t --rm --network=host -e ACCEPT_EULA=true -v ${pwd}/Demo:/mnt/Demo parasoft/soavirt soatestcli -property soatest.license.use_network=true -property license.network.url=$(license.server.url) -property license.network.use.specified.server=true -property license.netwrok.auth.enabled=true -property license.network.user=admin -property license.network.password=$(license.server.password) -property soatest.license.network.edition=automation_edition -config "user:// Example Configuration" -resource Demo'