# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: BatchScript@1
  inputs:
    filename: '"$(System.DefaultWorkingDirectory)\ado-soatestcli.bat"'
    modifyEnvironment: false
  displayName: 'Run a multi-line script'
