# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Set Up Project
steps:
- script: |
    mkdir temp 
    cp -R $(soatest.project) temp/.
    
    # Set Up and write localsetting.properties file
    echo $"
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=admin
    soatest.license.network.edition=automation_edition
    soatest.license.use_network=true
    virtualize.license.network.edition=performance_server_edition
    virtualize.license.use_network=true" >> temp/localsettings.properties
    ls -R
    cat temp/localsettings.properties
  displayName: "Set Up the /temp/localsettings.properties file"

# Mount Settings and Tests and Run
- script: |
    ls -R
    docker --version
    docker run -t \
    -e ACCEPT_EULA=true \
    -v "$(Build.Repository.LocalPath)/temp:/temp" \
    parasoft/soavirt /bin/bash -c " \
    ls /temp; \
    cat /temp/localsettings.properties; \
    soatestcli -import '/temp/Demo'; \
    ls -R '/temp/Demo'
    ls -R '/usr/local/parasoft/parasoft/soavirt_workspace/'; \
    soatestcli \
    -config 'user://Example Configuration' \
    -resource Demo \
    -settings /temp/localsettings.properties \
    "
  displayName: Mount the Project contents to SOAtest CLI Docker Container adn Run tests 