# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

steps:
- task: Docker@2
  displayName: run
  inputs: 
    command: run
    arguments: '-t -e ACCEPT_EULA=true parasoft/soavirt soatestcli -import ./Demo'
- task: Docker@2
  displayName: run
  inputs: 
    command: run
    arguments: '-t --rm -e ACCEPT_EULA=true parasoft/soavirt soatestcli -property soatest.license.use_network=true -property license.network.url=$(license.server.url) -property license.network.user=admin -property license.network.password=$(license.server.password) -config "user:// Example Configuration" -resource Demo'