# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker --version
    docker run -i \
    --net=host \
    -e ACCEPT_EULA=true \
    parasoft/soavirt soatestli \
    -machineid
    sleep 30
    docker container ls
    echo $( \
    docker exec -i \
    parasoft/soavirt soatestcli \
    -config "user:// Example Configuration" \
    -resource TestAssets \
    -property soatest.license.use_network=true \
    -property license.network.url=$(license.server.url) \
    -property license.network.use.specified.server=true \
    -property license.netwrok.auth.enabled=true \
    -property license.network.user=admin \
    -property license.network.password=$(license.server.password) \
    -property soatest.license.network.edition=automation_edition \
    )

### Import project into the workspace
# - task: Docker@2
#   displayName: run
#   inputs: 
#     command: run
#     arguments: '-t --network=host -e ACCEPT_EULA=true -v ${pwd}/Demo:/mnt/Demo parasoft/soavirt soatestcli -import /mnt/Demo'

### Run Project
# - task: Docker@2
#   displayName: run
#   inputs: 
#     command: run
#     arguments: '-t --rm --network=host -e ACCEPT_EULA=true -v ${pwd}/Demo:/mnt/Demo parasoft/soavirt soatestcli -property soatest.license.use_network=true -property license.network.url=$(license.server.url) -property license.network.use.specified.server=true -property license.netwrok.auth.enabled=true -property license.network.user=admin -property license.network.password=$(license.server.password) -property soatest.license.network.edition=automation_edition -config "user:// Example Configuration" -resource Demo'